#!/usr/bin/env python3
"""
Generates the synthetic statement fixtures bundled with the app.

Every name, account number, and amount is fictional. The output PDFs are
rendered through headless Chrome so they carry real extractable text, which
is what PDFKit reads — a scanned image would not work.

Four consecutive months are generated on purpose: RecurringChargeDetector
requires at least three occurrences of a charge before it will call it
recurring, so a single statement demonstrates nothing.

Usage: ./samples/generate-statements.py
"""

import subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "Tabs" / "SampleStatements"
WORK = ROOT / "samples" / "build"
CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

MONTHS = [(3, "Mar", 31), (4, "Apr", 30), (5, "May", 31), (6, "Jun", 30)]

# (day, description, amount-by-month-index or fixed amount)
RECURRING = [
    (2,  "NETFLIX.COM",                             15.49),
    (5,  "SPOTIFY USA  NEW YORK NY",                11.99),
    (8,  "HULU 877-8244808 CA",       [17.99, 17.99, 18.99, 18.99]),  # price rise
    (12, "ICLOUD+ APPLE.COM/BILL CUPERTINO CA",      2.99),
    (22, "YOUTUBEPREMIUM GOOGLE  G.CO/HELPPAY",     13.99),
    (25, "DISNEY PLUS 888-905 CA",                  13.99),
    (27, "COMCAST XFINITY 800-COMCAST",             79.00),
    (30, "PLANET FITNESS CLUB DUES",                24.99),
]

# Recurs on a regular cadence but the amount moves — exercises the
# "Amounts vary — looks one-off" near-miss path.
VARYING = (6, "SHELL OIL 57311 HOUSTON TX", [52.30, 47.85, 61.20, 44.90])

# One-off noise, different every month, so detection has something to reject.
NOISE = [
    [(3, "WHOLEFDS MKT #10293 AUSTIN TX", 84.12), (18, "TRADER JOES #455 PORTLAND OR", 63.77),
     (20, "STARBUCKS STORE 04713 SEATTLE WA", 6.45), (29, "UBER EATS  8005928996 CA", 28.40)],
    [(4, "SAFEWAY #1122 DENVER CO", 71.08), (16, "CHIPOTLE 2284 CHICAGO IL", 14.85),
     (21, "AMAZON MKTPLACE PMTS AMZN.COM/BILL WA", 36.41), (28, "DELTA AIR 0062281 ATLANTA GA", 318.40)],
    [(7, "COSTCO WHSE #0421 KIRKLAND WA", 142.63), (14, "SHAKE SHACK 0912 NEW YORK NY", 22.10),
     (19, "HOME DEPOT #4412 ATLANTA GA", 96.55), (26, "LYFT *RIDE 8887 SAN FRANCISCO CA", 18.75)],
    [(9, "TRADER JOES #455 PORTLAND OR", 58.92), (15, "AMAZON MKTPLACE PMTS AMZN.COM/BILL WA", 47.20),
     (23, "SWEETGREEN 0330 BOSTON MA", 16.40), (28, "SHELL OIL 22190 DALLAS TX", 39.15)],
]

# An annual charge; it appears once, so it correctly stays undetected.
ANNUAL = (3, 15, "AMAZON PRIME*T45830NQ3 AMZN.COM/BILL WA", 151.68)

CSS = """
  @page { size: letter; margin: 0.75in; }
  body { font-family: "Helvetica Neue", Arial, sans-serif; color: #111; font-size: 12px; }
  .head { display: flex; justify-content: space-between; border-bottom: 2px solid #111; padding-bottom: 10px; }
  .bank { font-size: 20px; font-weight: 700; letter-spacing: 0.5px; }
  .muted { color: #555; }
  h2 { font-size: 13px; margin: 22px 0 6px; text-transform: uppercase; letter-spacing: 0.4px; }
  pre { font-family: "SF Mono", Menlo, Consolas, monospace; font-size: 12px; line-height: 1.6; white-space: pre; }
  .summary td { padding: 2px 18px 2px 0; }
"""


def amount_for(spec, index):
    return spec[index] if isinstance(spec, list) else spec


def rows_for(index):
    month_num, _, _ = MONTHS[index]
    rows = [(day, desc, amount_for(spec, index)) for day, desc, spec in RECURRING]
    day, desc, amounts = VARYING
    rows.append((day, desc, amounts[index]))
    rows.extend(NOISE[index])
    if ANNUAL[0] == month_num:
        rows.append((ANNUAL[1], ANNUAL[2], ANNUAL[3]))
    return sorted(rows, key=lambda r: r[0])


def build_html(index):
    month_num, month_name, last_day = MONTHS[index]
    rows = rows_for(index)
    total = sum(r[2] for r in rows)
    lines = ["Date   Description                                Amount"]
    for day, desc, amt in rows:
        lines.append(f"{month_num:02d}/{day:02d}  {desc:<42} ${amt:,.2f}")
    return f"""<!doctype html>
<!--
  Synthetic bank statement for demoing Tabs. All names, numbers, and amounts
  are fictional. Generated by samples/generate-statements.py — edit that, not
  this file.
-->
<html>
<head><meta charset="utf-8"><style>{CSS}</style></head>
<body>
  <div class="head">
    <div>
      <div class="bank">Summit Federal Bank</div>
      <div class="muted">Cardholder Statement</div>
    </div>
    <div class="muted" style="text-align:right">
      Account ending 4821<br>
      Statement period: {month_name} 1 &ndash; {month_name} {last_day}, 2026<br>
      Page 1 of 1
    </div>
  </div>
  <h2>Account Summary</h2>
  <table class="summary">
    <tr><td>Previous Balance</td><td>$0.00</td></tr>
    <tr><td>Payments &amp; Credits</td><td>$0.00</td></tr>
    <tr><td>New Charges</td><td>${total:,.2f}</td></tr>
    <tr><td>New Balance</td><td>${total:,.2f}</td></tr>
  </table>
  <h2>Transactions</h2>
<pre>
{chr(10).join(lines)}
</pre>
</body>
</html>
"""


def main():
    if not Path(CHROME).exists():
        sys.exit(f"error: headless Chrome not found at {CHROME}")
    OUT.mkdir(parents=True, exist_ok=True)
    WORK.mkdir(parents=True, exist_ok=True)
    for i, (month_num, month_name, _) in enumerate(MONTHS):
        stem = f"summit-2026-{month_num:02d}"
        html = WORK / f"{stem}.html"
        pdf = OUT / f"{stem}.pdf"
        html.write_text(build_html(i))
        subprocess.run([CHROME, "--headless=new", "--disable-gpu", "--no-pdf-header-footer",
                        f"--print-to-pdf={pdf}", str(html)],
                       check=True, capture_output=True)
        print(f"wrote {pdf.relative_to(ROOT)}  ({month_name} 2026, {len(rows_for(i))} transactions)")


if __name__ == "__main__":
    main()
